version: '3'
services:
  database:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_DB: sirius-backend-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - database:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: 'Dockerfile'
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 8080 -b '0.0.0.0'"
    environment:
      - DB_URL=postgresql://postgres:postgres@database:5432/sirius-backend-db
      - RAILS_ENV=development
    ports:
      - "8080:8080"
    depends_on:
      - database
    volumes:
      - .:/app

volumes:
  database:
    driver: local
