version: '3'
services:
  db:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      - DB_URL=postgresql://postgres:postgres@database:5432/sirius-backend-db
      - RAILS_ENV=development
    ports:
      - "3001:3000"
    depends_on:
      - db
    volumes:
      - .:/rails-be-conditioner
